name: rainbow_puzzle
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.0.4
  oktoast: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path: "lib/icon.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
     - lib/icon.png

